name: fightladder
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1w=h7f8727e_0
  - pip=23.0.1=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.1.2=h7f8727e_1
  - setuptools=66.0.0=py38h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==1.4.0
    - alembic==1.13.1
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==23.1.0
    - av==10.0.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - blessed==1.20.0
    - cachetools==5.3.0
    - certifi==2022.12.7
    - cffi==1.15.1
    - charset-normalizer==3.3.2
    - cloudpickle==2.2.1
    - cmake==3.26.3
    - colorlog==6.8.2
    - comm==0.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - ecos==2.0.12
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - filelock==3.12.0
    - fonttools==4.39.3
    - fqdn==1.5.1
    - fsspec==2023.4.0
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - gpustat==1.1.1
    - greenlet==3.0.3
    - grpcio==1.54.0
    - gym==0.21.0
    - gym-retro==0.8.0
    - idna==3.6
    - imageio==2.34.0
    - importlib-metadata==4.13.0
    - importlib-resources==5.12.0
    - ipykernel==6.22.0
    - ipython==8.12.1
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.3.2
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.2.0
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - kiwisolver==1.4.4
    - lit==16.0.2
    - mako==1.3.2
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - mpmath==1.3.0
    - natsort==8.4.0
    - nbclassic==0.5.6
    - nbclient==0.7.4
    - nbconvert==7.3.1
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - networkx==3.0
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-ml-py==12.535.133
    - nvidia-nccl-cu11==2.19.3
    - nvidia-nvtx-cu11==11.8.86
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - optuna==3.5.0
    - packaging==23.1
    - pandas==2.0.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.5.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==4.22.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pyglet==1.5.27
    - pygments==2.15.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.0.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - sb3-contrib==1.7.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - sqlalchemy==2.0.27
    - stable-baselines3==1.7.0
    - stack-data==0.6.2
    - sympy==1.12
    - tensorboard==2.12.1
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - torch==2.2.0+cu118
    - torchaudio==2.2.0+cu118
    - torchvision==0.17.0+cu118
    - tornado==6.3.1
    - tqdm==4.66.1
    - traitlets==5.9.0
    - triton==2.2.0
    - typing-extensions==4.10.0
    - tzdata==2023.3
    - uri-template==1.2.0
    - urllib3==2.2.1
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.2.3
    - zipp==3.15.0
